apiVersion : apps/v1
kind: Deployment
metadata:
  name: hueborgwebreactapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hueborgwebreactapp
  template:
    metadata:
      labels:
        app: hueborgwebreactapp 
    spec:
      containers:
        - name: hueborgwebreactapp 
          image: sapcwdockerregistryname.azurecr.io/hueborgwebreactapp
          ports:
          - containerPort: 3000