name: learn-github-actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2

    - name: Use Node.js v18.19.0
      uses: actions/setup-node@v4
      with:
        node-version: 18.19.0

    - name: Install dependencies
      run: yarn install

    - name: Build React application
      run: yarn build
